# Generated by Django 5.2.17 on 2026-09-28 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text="Déjalo vacío y se genera solo (ej.: SIE-CAN-M-POL-M-01)",
                        max_length=40,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                (
                    "talla",
                    models.CharField(
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                            ("U", "Única"),
                            ("4", "Infantil 4"),
                            ("6", "Infantil 6"),
                            ("8", "Infantil 8"),
                            ("10", "Infantil 10"),
                            ("12", "Infantil 12"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("reservado", "Reservado"),
                            ("alquilado", "Alquilado"),
                            ("en_lavado", "En lavado"),
                            ("en_mantenimiento", "En mantenimiento"),
                            ("danado", "Dañado"),
                            ("baja", "Dado de baja"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[
                            ("nuevo", "Nuevo"),
                            ("bueno", "Bueno"),
                            ("regular", "Regular"),
                            ("desgastado", "Desgastado"),
                        ],
                        default="bueno",
                        max_length=12,
                        verbose_name="condición",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        help_text="Ej.: Percha A3",
                        max_length=60,
                        verbose_name="ubicación",
                    ),
                ),
                (
                    "fecha_adquisicion",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de adquisición"
                    ),
                ),
                (
                    "costo_adquisicion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="costo de adquisición",
                    ),
                ),
                ("veces_alquilada", models.PositiveIntegerField(default=0)),
                ("notas", models.TextField(blank=True)),
                (
                    "prenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unidades",
                        to="catalogo.prenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "unidad de inventario",
                "verbose_name_plural": "unidades de inventario",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado_anterior", models.CharField(blank=True, max_length=20)),
                ("estado_nuevo", models.CharField(max_length=20)),
                ("motivo", models.CharField(max_length=200)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="inventario.unidadinventario",
                    ),
                ),
            ],
            options={
                "verbose_name": "cambio de estado",
                "verbose_name_plural": "historial de estados",
                "ordering": ["-fecha"],
            },
        ),
    ]
