# Generated by Django 5.2.17 on 2026-09-28 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_tipoprenda_prenda_tipo_prenda_disenoprenda"),
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadinventario",
            name="diseno",
            field=models.ForeignKey(
                blank=True,
                help_text="Debe ser un diseño de la prenda elegida",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unidades",
                to="catalogo.disenoprenda",
                verbose_name="diseño o color",
            ),
        ),
    ]
