# Generated by Django 5.2.17 on 2026-09-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_unidadinventario_diseno"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadinventario",
            name="busto_cm",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="busto (cm)"
            ),
        ),
        migrations.AddField(
            model_name="unidadinventario",
            name="cadera_cm",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="cadera (cm)"
            ),
        ),
        migrations.AddField(
            model_name="unidadinventario",
            name="cintura_cm",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="cintura (cm)"
            ),
        ),
        migrations.AddField(
            model_name="unidadinventario",
            name="largo_cm",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="largo (cm)"
            ),
        ),
    ]
