# Generated by Django 5.2.17 on 2026-09-29 00:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alquileres", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("anticipo", "Anticipo"),
                            ("saldo", "Saldo"),
                            ("garantia", "Garantía"),
                            ("cargo", "Cargo por daño o faltante"),
                            ("devolucion_garantia", "Devolución de garantía"),
                        ],
                        default="anticipo",
                        max_length=20,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia"),
                            ("pasarela", "Pasarela de pago"),
                        ],
                        default="transferencia",
                        max_length=15,
                        verbose_name="método",
                    ),
                ),
                (
                    "comprobante",
                    models.FileField(
                        blank=True,
                        help_text="Imagen o PDF",
                        upload_to="comprobantes/%Y/%m/",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("por_validar", "Por validar"),
                            ("validado", "Validado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="por_validar",
                        max_length=12,
                    ),
                ),
                (
                    "motivo_rechazo",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="motivo del rechazo"
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "fecha_validacion",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="fecha de validación",
                    ),
                ),
                (
                    "alquiler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="alquileres.alquiler",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "pago",
                "verbose_name_plural": "pagos",
                "ordering": ["-fecha"],
            },
        ),
    ]
