# Generated by Django 5.2.17 on 2026-09-28 19:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Localidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej.: Cañar, Otavalo, Trajes de gala", max_length=80
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=90, unique=True)),
                (
                    "descripcion_cultural",
                    models.TextField(blank=True, verbose_name="descripción cultural"),
                ),
                ("imagen", models.ImageField(blank=True, upload_to="localidades/")),
            ],
            options={
                "verbose_name": "localidad",
                "verbose_name_plural": "localidades",
                "ordering": ["region__orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="nombre"),
                ),
                ("slug", models.SlugField(blank=True, max_length=60, unique=True)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("imagen", models.ImageField(blank=True, upload_to="regiones/")),
                (
                    "orden",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Orden en el menú del catálogo"
                    ),
                ),
            ],
            options={
                "verbose_name": "región",
                "verbose_name_plural": "regiones",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ModeloTraje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="Ej.: Traje de Cañar", max_length=100),
                ),
                ("slug", models.SlugField(blank=True, max_length=110, unique=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("danza", "Danza tradicional"),
                            ("certamen", "Certamen y reinas"),
                        ],
                        default="danza",
                        max_length=10,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "solo_completo",
                    models.BooleanField(
                        default=False,
                        help_text="Se activa solo en certámenes: no se ofrecen prendas sueltas (RN-25).",
                        verbose_name="solo se alquila completo",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Desmarca para ocultarlo del catálogo"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modelos",
                        to="catalogo.localidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "modelo de traje",
                "verbose_name_plural": "modelos de traje",
                "ordering": ["localidad__region__orden", "localidad__nombre", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="localidad",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localidades",
                to="catalogo.region",
                verbose_name="región",
            ),
        ),
        migrations.CreateModel(
            name="VarianteGenero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("mujer", "Mujer"),
                            ("hombre", "Hombre"),
                            ("infantil", "Infantil"),
                        ],
                        max_length=10,
                        verbose_name="género",
                    ),
                ),
                (
                    "precio_completo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="precio traje completo",
                    ),
                ),
                (
                    "garantia_completo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="garantía traje completo",
                    ),
                ),
                (
                    "dias_buffer_lavado",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Días que la prenda no se alquila tras la devolución",
                        verbose_name="días de lavado",
                    ),
                ),
                (
                    "foto_principal",
                    models.ImageField(
                        blank=True,
                        help_text="Traje completo con sus accesorios",
                        upload_to="trajes/",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variantes",
                        to="catalogo.modelotraje",
                    ),
                ),
            ],
            options={
                "verbose_name": "variante por género",
                "verbose_name_plural": "variantes por género",
                "ordering": ["modelo", "genero"],
            },
        ),
        migrations.CreateModel(
            name="Prenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej.: Pollera, Poncho, Collar", max_length=60
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("prenda", "Prenda"), ("accesorio", "Accesorio")],
                        default="prenda",
                        max_length=10,
                    ),
                ),
                (
                    "precio_individual",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="precio individual",
                    ),
                ),
                (
                    "garantia_individual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="garantía individual",
                    ),
                ),
                (
                    "incluida_sin_costo",
                    models.BooleanField(
                        default=False,
                        help_text="Marca para collar y aretes que van gratis en el traje completo",
                        verbose_name="incluida sin costo",
                    ),
                ),
                (
                    "cantidad_por_traje",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="cantidad por traje"
                    ),
                ),
                ("foto", models.ImageField(blank=True, upload_to="prendas/")),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prendas",
                        to="catalogo.variantegenero",
                    ),
                ),
            ],
            options={
                "verbose_name": "prenda",
                "verbose_name_plural": "prendas",
                "ordering": ["variante", "tipo", "nombre"],
            },
        ),
        migrations.AddConstraint(
            model_name="localidad",
            constraint=models.UniqueConstraint(
                fields=("region", "nombre"), name="localidad_unica_por_region"
            ),
        ),
        migrations.AddConstraint(
            model_name="variantegenero",
            constraint=models.UniqueConstraint(
                fields=("modelo", "genero"), name="variante_unica_por_genero"
            ),
        ),
        migrations.AddConstraint(
            model_name="prenda",
            constraint=models.UniqueConstraint(
                fields=("variante", "nombre"), name="prenda_unica_por_variante"
            ),
        ),
    ]
