# Generated by Django 5.2.17 on 2026-09-28 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoPrenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej.: Blusa, Pollera, Sombrero, Poncho",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "tipo de prenda",
                "verbose_name_plural": "tipos de prenda",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="prenda",
            name="tipo_prenda",
            field=models.ForeignKey(
                help_text="Agrupa la prenda en la pestaña Prendas individuales",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prendas",
                to="catalogo.tipoprenda",
                verbose_name="tipo de prenda",
            ),
        ),
        migrations.CreateModel(
            name="DisenoPrenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej.: Bordada fucsia, Blanca con encaje",
                        max_length=60,
                        verbose_name="diseño o color",
                    ),
                ),
                ("foto", models.ImageField(blank=True, upload_to="disenos/")),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Desmarca para ocultarlo del catálogo"
                    ),
                ),
                (
                    "prenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disenos",
                        to="catalogo.prenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "diseño de prenda",
                "verbose_name_plural": "diseños de prenda",
                "ordering": ["prenda", "nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prenda", "nombre"), name="diseno_unico_por_prenda"
                    )
                ],
            },
        ),
    ]
