# Generated by Django 5.2.17 on 2026-09-29 00:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "porcentaje_anticipo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="anticipo para reservar (%)",
                    ),
                ),
                (
                    "dias_retiro_antes",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="días de retiro antes del evento"
                    ),
                ),
                (
                    "dias_devolucion_despues",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="días de devolución después del evento"
                    ),
                ),
                (
                    "dias_cancelacion",
                    models.PositiveSmallIntegerField(
                        default=7,
                        verbose_name="días mínimos para cancelar con devolución del anticipo",
                    ),
                ),
                (
                    "recargo_diario_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="recargo por día de atraso (%)",
                    ),
                ),
                (
                    "descuento_parejas_activo",
                    models.BooleanField(
                        default=True, verbose_name="descuento por parejas activo"
                    ),
                ),
                (
                    "minimo_parejas",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="mínimo de parejas para el descuento"
                    ),
                ),
                (
                    "descuento_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="descuento por parejas (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuración",
                "verbose_name_plural": "configuración",
            },
        ),
    ]
