# Generated by Django 5.2.17 on 2026-09-29 00:11

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alquileres", "0001_extension_btree_gist"),
        ("catalogo", "0002_tipoprenda_prenda_tipo_prenda_disenoprenda"),
        ("cuentas", "0001_initial"),
        ("inventario", "0002_unidadinventario_diseno"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alquiler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("individual", "Individual"), ("grupal", "Grupal")],
                        default="individual",
                        max_length=10,
                    ),
                ),
                ("fecha_evento", models.DateField(verbose_name="fecha del evento")),
                (
                    "fecha_retiro",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía y se calcula según la configuración",
                        null=True,
                        verbose_name="fecha de retiro",
                    ),
                ),
                (
                    "fecha_devolucion",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía y se calcula según la configuración",
                        null=True,
                        verbose_name="devolución pactada",
                    ),
                ),
                (
                    "fecha_devolucion_real",
                    models.DateField(
                        blank=True, null=True, verbose_name="devolución real"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente_pago", "Pendiente de pago"),
                            ("confirmado", "Confirmado"),
                            ("entregado", "Entregado"),
                            ("devuelto", "Devuelto"),
                            ("cerrado", "Cerrado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente_pago",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=10,
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=10,
                        verbose_name="descuento por parejas",
                    ),
                ),
                (
                    "recargos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="recargos por atraso",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=10,
                    ),
                ),
                (
                    "anticipo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=10,
                    ),
                ),
                (
                    "garantia_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=10,
                        verbose_name="garantía",
                    ),
                ),
                (
                    "estado_garantia",
                    models.CharField(
                        choices=[
                            ("por_cobrar", "Por cobrar"),
                            ("retenida", "Retenida"),
                            ("devuelta", "Devuelta"),
                            ("aplicada", "Aplicada parcialmente"),
                        ],
                        default="por_cobrar",
                        max_length=12,
                        verbose_name="estado de la garantía",
                    ),
                ),
                (
                    "autoriza_uso_imagen",
                    models.BooleanField(
                        default=False, verbose_name="autoriza uso de imagen"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alquileres",
                        to="cuentas.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "alquiler",
                "verbose_name_plural": "alquileres",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="LineaAlquiler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("traje", "Traje completo"),
                            ("prenda", "Prenda individual"),
                        ],
                        default="traje",
                        max_length=10,
                    ),
                ),
                (
                    "talla",
                    models.CharField(
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                            ("U", "Única"),
                            ("4", "Infantil 4"),
                            ("6", "Infantil 6"),
                            ("8", "Infantil 8"),
                            ("10", "Infantil 10"),
                            ("12", "Infantil 12"),
                        ],
                        max_length=3,
                    ),
                ),
                ("cantidad", models.PositiveSmallIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=10,
                        verbose_name="precio unitario",
                    ),
                ),
                (
                    "alquiler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="alquileres.alquiler",
                    ),
                ),
                (
                    "diseno",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo para prenda individual",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.disenoprenda",
                        verbose_name="diseño de prenda",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo para traje completo",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.variantegenero",
                        verbose_name="traje",
                    ),
                ),
            ],
            options={
                "verbose_name": "línea del alquiler",
                "verbose_name_plural": "líneas del alquiler",
            },
        ),
        migrations.CreateModel(
            name="AsignacionUnidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo",
                    django.contrib.postgres.fields.ranges.DateRangeField(
                        help_text="Desde el retiro hasta la devolución más los días de lavado"
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True, help_text="Se desactiva si el alquiler se cancela"
                    ),
                ),
                ("entregada", models.BooleanField(default=False)),
                (
                    "condicion_retorno",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("correcta", "Correcta"),
                            ("sucia", "Sucia"),
                            ("danada", "Dañada"),
                            ("faltante", "Faltante"),
                        ],
                        max_length=10,
                        verbose_name="condición al volver",
                    ),
                ),
                (
                    "cargo",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones",
                        to="inventario.unidadinventario",
                    ),
                ),
                (
                    "linea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="alquileres.lineaalquiler",
                    ),
                ),
            ],
            options={
                "verbose_name": "unidad asignada",
                "verbose_name_plural": "unidades asignadas",
                "constraints": [
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("activa", True)),
                        expressions=[("unidad", "="), ("periodo", "&&")],
                        name="unidad_sin_fechas_cruzadas",
                    )
                ],
            },
        ),
    ]
