# Generated by Django 5.2.17 on 2026-09-29 00:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("persona", "Persona"),
                            ("institucion", "Institución educativa"),
                            ("grupo", "Grupo de danza"),
                        ],
                        default="persona",
                        max_length=12,
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "cedula_ruc",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}(\\d{3})?$",
                                "Escribe 10 dígitos (cédula) o 13 dígitos (RUC), sin guiones.",
                            )
                        ],
                        verbose_name="cédula o RUC",
                    ),
                ),
                ("telefono", models.CharField(max_length=20, verbose_name="WhatsApp")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="dirección"
                    ),
                ),
                (
                    "institucion",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="institución"
                    ),
                ),
                (
                    "bloqueado",
                    models.BooleanField(
                        default=False,
                        help_text="Un cliente bloqueado no puede reservar en línea",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        help_text="Solo si el cliente creó su cuenta",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["nombre"],
            },
        ),
    ]
